mysite/kasse/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from . import views

app_name = 'kasse'
urlpatterns = [    
    path('', views.Index, name='index'),
    path('supplier/', views.Suppliers, name='supplier'),
    path('statistics/', views.Statistics, name='statistics'),
    path('myorders/', views.Myorders, name='myorders'),
    path('orders/<int:pk>/', views.Orderdetail, name='orderdetail'),
    path('accounting/', views.Accounting, name='accounting'),
    path('deposit/', views.deposit, name='deposit'),
    path('<int:order_id>/order/', views.order, name='order'),
    path('delete_orderitem/<int:orderitem_id>/<int:order_id>/', views.delete_orderitem, name='delete_orderitem'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('kasse.urls')),    
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/kasse/models.py
from datetime import timedelta

from django.contrib.auth.models import User
from django.db import models
from django.db.models import F
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils import timezone
from django.core.mail import send_mail
from django.conf import settings

class Usersaldo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    saldo = models.DecimalField(decimal_places=2, max_digits=5, default='0')    


class Supplier(models.Model):
    name = models.CharField(max_length=200)
    menu = models.ImageField(upload_to='menus', null=True, blank=True)
    menulink = models.CharField(max_length=300, default='')

    def __str__(self):
        return self.name


class Orders(models.Model):    
    end_time = timezone.now() + timedelta(hours=2)
    start_date = models.DateTimeField(default=timezone.now)
    end_date = models.DateTimeField(default=end_time)
    supplier = models.ForeignKey(Supplier, on_delete=models.CASCADE)
    deliverytime = models.DateTimeField(default=end_time)
    active = models.BooleanField(default=True)
    deactivate_date = models.DateTimeField(blank=True, null=True)

    def __str__(self):
        order_name = self.supplier.name + '_' + str(self.start_date)
        return order_name


class OrderItems(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    original_value = models.DecimalField(decimal_places=2, max_digits=5)
    value = models.DecimalField(decimal_places=2, max_digits=5)
    title = models.CharField(max_length=200)
    ordernumber = models.IntegerField(default=0)
    order = models.ForeignKey(Orders, on_delete=models.CASCADE)


class DiscountRules(models.Model):
    operator_choices = (('=', '='),
                        ('*', '*'),
                        ('+', '+'),
                        ('-', '-'))
    supplier = models.ForeignKey(Supplier, on_delete=models.CASCADE)
    orderitems = models.CharField(max_length=999)
    discount_operator = models.CharField(
        max_length=2, choices=operator_choices)
    discount_value = models.FloatField(default=0)

    def __str__(self):
        return self.supplier.name+str(self.id)


class Deposit(models.Model):    
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    value = models.DecimalField(decimal_places=2, max_digits=5)
    accepted = models.BooleanField(default=False)
    accepted_date = models.DateTimeField(blank=True, null=True)
    deposit_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        deposit_name = self.user.username + '_' + str(self.deposit_date)
        return deposit_name


@receiver(post_save, sender=User)
def modify_new_user(sender, instance, created, **kwargs):
    if created:
        try:
            Usersaldo.objects.create(user=instance)
        except Exception as e:
            print(e)


@receiver(post_save, sender=Deposit)
def add_deposit_to_user(sender, instance, **kwargs):    
    if instance.accepted_date is None and instance.accepted is True:
        try:
            Usersaldo.objects.filter(user=instance.user).update(
                saldo=F('saldo') + instance.value)
            Deposit.objects.filter(pk=instance.id).update(
                accepted_date=timezone.now())
        except Exception as e:
            print(e)


@receiver(post_save, sender=Orders)
def calculate_debits_for_user(sender, instance, **kwargs):    
    if instance.deactivate_date is None and not instance.active:
        for item in instance.orderitems_set.all():
            try:
                Usersaldo.objects.filter(user=item.user).update(
                    saldo=F('saldo') - item.value)
                Orders.objects.filter(pk=instance.id).update(
                    deactivate_date=timezone.now())
            except Exception as e:
                print(e)

mysite/kasse/forms.py
# -*- coding: utf-8 -*-

from django import forms


class DocumentForm(forms.Form):
    docfile = forms.FileField(
        label='Select a file'
)

mysite/kasse/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.models import User
from django.db.models import Sum, Count
import re

from .models import Orders, Supplier, OrderItems, Deposit


@login_required
def order(request, order_id):
    order_id = order_id
    user = User.objects.get(username=request.user.username)
    title = request.POST.get("orderitem")
    ordernumber = request.POST.get("ordernumber")
    original_value = float(request.POST.get(
        "orderitem_value").replace(',', '.'))
    lorder = get_object_or_404(Orders, pk=order_id)
    discount_rules = lorder.supplier.discountrules_set.all()
    value = original_value
    for rule in discount_rules:
        items = rule.orderitems
        operator = rule.discount_operator
        discount_value = rule.discount_value
        if re.match(ordernumber, items):
            if operator == '+':
                value = value + discount_value
            elif operator == '-':
                value = value - discount_value
            elif operator == '*':
                value = value * discount_value
            elif operator == '=':
                value = discount_value
    try:
        lorder.orderitems_set.create(user=user, title=title, original_value=original_value,
                                     value=value, order=lorder.id, ordernumber=ordernumber)
    except Exception as e:
        print(e)
    return HttpResponseRedirect(reverse('kasse:orderdetail', args=(lorder.id,)))


@login_required
def delete_orderitem(request, orderitem_id, order_id):
    user = User.objects.get(username=request.user.username)
    try:
        OrderItems.objects.filter(id=orderitem_id).delete()
    except Exception as e:
        print(e)
    return HttpResponseRedirect(reverse('kasse:orderdetail', args=(order_id,)))


@login_required
def Index(request):
    order_list = Orders.objects.filter(active=True)
    user = User.objects.get(username=request.user.username)
    saldo = user.usersaldo.saldo
    context = {'order_list': order_list,
               'user': request.user.username,
               'saldo': str(saldo)}
    return render(request, 'kasse/index.html', context)


@login_required
def Suppliers(request):
    supplier_list = Supplier.objects.order_by('name')
    user = User.objects.get(username=request.user.username)
    saldo = user.usersaldo.saldo
    context = {'supplier_list': supplier_list,
               'user': request.user.username,
               'saldo': str(saldo)}
    return render(request, 'kasse/supplier.html', context)


@login_required
def Statistics(request):
    order_list = Orders.objects.order_by('-start_date')[:30]
    user = User.objects.get(username=request.user.username)
    saldo = user.usersaldo.saldo
    topten = Supplier.objects.annotate(
        num_orders=Count('orders')).order_by('-num_orders')[:10]
    context = {'order_list': order_list,
               'user': request.user.username,
               'saldo': str(saldo),
               'topten': topten}
    return render(request, 'kasse/statistics.html', context)


@login_required
def Orderdetail(request, pk):
    order = get_object_or_404(Orders, pk=pk)
    orderitems = OrderItems.objects.all().filter(order=order.id)
    summary = OrderItems.objects.all().filter(order=order).aggregate(Sum('value'))
    user = User.objects.get(username=request.user.username)
    saldo = user.usersaldo.saldo
    context = {'order': order,
               'orderitems': orderitems,
               'summary': summary['value__sum'],
               'user': request.user.username,
               'saldo': str(saldo)}
    return render(request, 'kasse/orderdetails.html', context)


@login_required
def Myorders(request):
    user = User.objects.get(username=request.user.username)
    saldo = user.usersaldo.saldo
    orderitems = OrderItems.objects.all().filter(user=user.id)
    context = {'orderitems': orderitems,
               'user': request.user.username,
               'saldo': str(saldo)}
    return render(request, 'kasse/myorders.html', context)


@login_required
def Accounting(request):
    user = User.objects.get(username=request.user.username)
    saldo = user.usersaldo.saldo
    deposits = Deposit.objects.all().filter(user=user).order_by('-deposit_date')
    context = {'user': request.user.username,
               'saldo': str(saldo),
               'deposits': deposits}
    return render(request, 'kasse/accounting.html', context)


@login_required
def deposit(request):
    user = User.objects.get(username=request.user.username)
    value = float(request.POST.get("deposit_value").replace(',', '.'))
    try:
        Deposit.objects.create(user=user, value=value)
    except Exception as e:
        print(e)
    return HttpResponseRedirect(reverse('kasse:accounting'))

mysite/kasse/templates/kasse/accounting.html
{% extends "kasse/base.html" %} {% block usersaldo %}
<ul class="nav navbar-nav navbar-right">
    {% if saldo != None %}
    <li><a class="nav-link" href="{% url 'kasse:accounting' %}"> {{user}} ({{saldo}} EUR)</a></li>
    <li><a class="nav-link" href="/accounts/logout"> Logout</a></li>
    {% endif %}
</ul>
{% endblock %} {% block content %}

<main>
    <div class="container">
        <h4>Einzahlung tätigen</h4>
        <p>Bevor die Einzahlung berechnet wird, muss diese durch einen Kassenwart manuell bestätigt werden</p>
        <form class="form-inline" action="{% url 'kasse:deposit' %}" method="post">
            {% csrf_token %}
            <div class="form-group ">
                <label for="deposit_value" class="col-sm-4 col-form-label">Einzahlungsumme: </label>
                <div class="col-sm-4">
                    <input type="text " class="form-control " name="deposit_value" id="deposit_value" value="5">
                </div>
            </div>
            <button type="submit " class="btn btn-default ">Submit</button>
        </form>
    </div>
    <div class="container" style="margin-top:15px">
        <h4>Unbestätigte Einzahlungen:</h4>
        <table class="table">
            <thead>
                <tr>
                    <th>Datum</th>
                    <th>Summe</th>
                    <th>Bestätigt</th>
                </tr>
            </thead>
            <tbody>
                {% if deposits %} {% for deposit in deposits %}
                <tr>
                    <td>{{deposit.deposit_date}}</td>
                    <td>{{deposit.value}}</td>
                    <td>{% if deposit.accepted %}
                        <p class="text-success">Akzeptiert</p>
                        {%else%}
                        <p class="text-warning">Noch nicht Akzeptiert</p>
                        {% endif %}</td>
                </tr>
                {% endfor%} {% else %}
                <tr>
                    <td>Keine</td>
                </tr>
                {% endif %}
            </tbody>
        </table>
    </div>
</main>
{% endblock %}

mysite/kasse/templates/kasse/base.html
<!DOCTYPE html>
<html lang="de">

<head>
    {% load bootstrap4 %} {% bootstrap_css %}
    <title>{% block title %}ESSEN!!{% endblock %}</title>
</head>

<body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
        <a class="navbar-brand" href="/">Essenskasse</a>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'kasse:myorders' %}">Meine Bestellungen</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'kasse:statistics' %}">Statistiken</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'kasse:supplier' %}">Lieferdienste</a>
                </li>
            </ul>
            {% block usersaldo %}{% endblock %}
        </div>
    </nav>
    <div id="content">
        {% block content %}{% endblock %}
    </div>

</body>

mysite/kasse/templates/kasse/index.html
{% extends "kasse/base.html" %} {% block usersaldo %}
<ul class="nav navbar-nav navbar-right">
    {% if saldo != None %}
    <li><a class="nav-link" href="{% url 'kasse:accounting' %}"> {{user}} ({{saldo}} EUR)</a></li>
    <li><a class="nav-link" href="/accounts/logout"> Logout</a></li>
    {% endif %}
</ul>
{% endblock %} {% block content %}
<main>
    <div class="container">
        <h3>Aktuelle Bestellungen:</h3>
        {% if order_list %} {% for order in order_list %}
        <p><a class="nav-link" href="{% url 'kasse:orderdetail' order.id %}">{{ order.supplier }}</a></p>
        {% endfor %} {% else %}
        <p>Aktuell laufen keine Bestellungen</p>
        {% endif %}
    </div>
</main>
{% endblock %}

mysite/kasse/templates/kasse/myorders.html
{% extends "kasse/base.html" %} {% block usersaldo %}
<ul class="nav navbar-nav navbar-right">
    {% if saldo != None %}
    <li><a class="nav-link" href="{% url 'kasse:accounting' %}"> {{user}} ({{saldo}} EUR)</a></li>
    <li><a class="nav-link" href="/accounts/logout"> Logout</a></li>
    {% endif %}
</ul>
{% endblock %} {% block content %}
<div class="container">
    <table class="table">
        <thead>
            <tr>
                <th>Datum / Lieferdienst</th>
                <th>Bestellt</th>
                <th>Preis in EUR</th>
            </tr>
        </thead>
        <tbody>
            {% if orderitems %} {% for orderitem in orderitems %}
            <tr>
                <td><a href="{% url 'kasse:orderdetail' orderitem.order.id %}">{{orderitem.order.start_date|date:"Y-m-d"}} {{orderitem.order.supplier}}</a></td>
                <td>{{orderitem.title}}</td>
                <td>{{orderitem.value}}</td>
            </tr>
            {% endfor%}
            <tr>
                <td><b>Gesamtsumme:</b></td>
                <td></td>
                <td><b>{{summary}}</b></td>
            </tr>{%else%}
            <tr>
                <td> Noch keine Bestellung erfolgt</td>
            </tr>
            {% endif %}
        </tbody>
    </table>


    {% endblock %}

mysite/kasse/templates/kasse/orderdetails.html
{% extends "kasse/base.html" %} {% block usersaldo %}
<ul class="nav navbar-nav navbar-right">
    {% if saldo != None %}
    <li><a class="nav-link" href="{% url 'kasse:accounting' %}"> {{user}} ({{saldo}} EUR)</a></li>
    <li><a class="nav-link" href="/accounts/logout"> Logout</a></li>
    {% endif %}
</ul>
{% endblock %} {% block content %}
<main>
    <div class="container">
        {% if order.supplier.menu %}
        <h3>Bestellung bei <a target="_blank" href={{order.supplier.menu.url}}>{{ order.supplier }}</a> bis {{order.end_date|date:'G:i'}} Uhr</h3>
        {% elif order.supplier.menulink %}
        <h3>Bestellung bei <a target="_blank" href={{order.supplier.menulink}}>{{ order.supplier }}</a> bis {{order.end_date|date:'G:i'}} Uhr</h3>
        {%else %}
        <h3>Bestellung bei {{ order.supplier }} bis {{order.end_date|date:'G:i'}} Uhr</h3>
        {%endif%} {% if order.active %}
        <form class="form-inline" action="{% url 'kasse:order' order.id %}" method="post">
            {% csrf_token %}
            <div class="form-group ">
                <label for="ordernumber " class="col-sm-4 col-form-label">Bestellnummer: </label>
                <div class="col-sm-4">
                    <input type="text " class="form-control " name="ordernumber" id="ordernumber " value="543 ">
                </div>
            </div>
            <div class="form-group ">
                <label for="orderitem " class="col-sm-4 col-form-label">Bestelltext: </label>
                <div class="col-sm-4">
                    <input type="text " class="form-control " name="orderitem" id="orderitem " value="Baguette">
                </div>
            </div>
            <div class="form-group ">
                <label for="orderitem_value " class="col-sm-4 col-form-label">Preis:</label>
                <div class="col-sm-4">
                    <input type="text " class="form-control " name="orderitem_value" id="orderitem_value " value="5,32 ">
                </div>
            </div>
            <div class="form-group">
                <button type="submit " class="btn btn-success">Submit</button>
            </div>
        </form>
        {% else %}
        <h5> Bestellung wurde bereits abgeschlossen. Vorrausichtliche Lieferzeit: {{ order.deliverytime }}</h5>
        {% endif%}
    </div>
    <div class="container">
        <table class="table">
            <thead>
                <tr>
                    <th>Nutzer</th>
                    <th>Bestellnummer</th>
                    <th>Bestelltext</th>
                    <th>Preis in EUR</th>
                    <th>MagiePreis in EUR</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                {% if orderitems %} {% for orderitem in orderitems %}
                <tr>
                    <td>{{orderitem.user}}</td>
                    <td>{{orderitem.ordernumber}}</td>
                    <td>{{orderitem.title}}</td>
                    <td>{{orderitem.original_value}}</td>
                    <td>{{orderitem.value}}</td>
                    {% if order.active %} {% if orderitem.user.username == request.user.username %}
                    <td><a class="btn btn-danger" role="button" href="{% url 'kasse:delete_orderitem' orderitem.id orderitem.order.id %}">DEL</a></td>
                    {% else %}
                    <td></td>
                    {% endif %} {% endif %}
                </tr>
                {% endfor%}
                <tr>
                    <td><b>Gesamtsumme:</b></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td><b>{{summary}}</b></td>
                </tr>{%else%}
                <tr>
                    <td> Noch keine Bestellung erfolgt</td>
                </tr>
                {% endif %}
            </tbody>
        </table>

    </div>
</main>
{% endblock %}

mysite/kasse/templates/kasse/statistics.html
{% extends "kasse/base.html" %} {% block usersaldo %}
<ul class="nav navbar-nav navbar-right">
    {% if saldo != None %}
    <li><a class="nav-link" href="{% url 'kasse:accounting' %}"> {{user}} ({{saldo}} EUR)</a></li>
    <li><a class="nav-link" href="/accounts/logout"> Logout</a></li>
    {% endif %}
</ul>
{% endblock %} {% block content %}
<main>
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                <h2>Bestellungen</h2>
                <table class="table table-condensed">
                    <thead>
                        <tr>
                            <th>Datum</th>
                            <th>Lieferant</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for order in order_list %}
                        <tr>
                            <td> {{ order.start_date|date:"Y-m-d"}} </td>
                            <td><a href="{% url 'kasse:orderdetail' order.id %}">{{ order.supplier }}</a>
                            </td>
                        </tr>{% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="col-lg-6">
                <h2>Top Ten Lieferanten</h2>
                <table class="table table-condensed  col-sm-6">
                    <thead>
                        <tr>
                            <th>Lieferant</th>
                            <th>Anzahl Bestellungen</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for supplier in topten %}
                        <tr>
                            <td> {{supplier}} </td>
                            <td>{{supplier.num_orders}}</a>
                            </td>
                        </tr>{% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</main>
{% endblock %}

mysite/kasse/templates/kasse/supplier.html
{% extends "kasse/base.html" %} {% block usersaldo %}
<ul class="nav navbar-nav navbar-right">
    {% if saldo != None %}
    <li><a class="nav-link" href="{% url 'kasse:accounting' %}"> {{user}} ({{saldo}} EUR)</a></li>
    <li><a class="nav-link" href="/accounts/logout"> Logout</a></li>
    {% endif %}
</ul>
{% endblock %} {% block content %}
<main>
    {% if supplier_list %}
    <ul>
        {% for supplier in supplier_list %}
        <li> {{ supplier.name }} {% if supplier.menu %}->
            <a target="_blank" href={{supplier.menu.url}}>Karte</a> {% elif supplier.menulink != ''%}->
            <a target="_blank" href={{supplier.menulink}}>Link</a> {% endif %}
        </li>
        {% endfor %}
    </ul>
    {% else %}
    <p>Keine Lieferanten hinterlegt</p>
    {% endif %}
</main>
{% endblock %}